import { RealisationsService } from './realisations.service';
import { CreateRealisationDto, UpdateRealisationDto, RealisationQueryDto } from './dto';
export declare class RealisationsController {
    private realisationsService;
    constructor(realisationsService: RealisationsService);
    findAll(query: RealisationQueryDto): Promise<{
        data: {
            tags: string[];
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            location: string;
            slug: string;
            date: string;
            titleFr: string;
            titleEn: string | null;
            scope: string;
            descFr: string;
            descEn: string | null;
            images: string[];
            client: string | null;
            isFeatured: boolean;
            order: number;
        }[];
        meta: {
            total: number;
            page: number;
            perPage: number;
            totalPages: number;
        };
    }>;
    findOne(id: string): Promise<{
        tags: string[];
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        location: string;
        slug: string;
        date: string;
        titleFr: string;
        titleEn: string | null;
        scope: string;
        descFr: string;
        descEn: string | null;
        images: string[];
        client: string | null;
        isFeatured: boolean;
        order: number;
    }>;
    create(createDto: CreateRealisationDto, req: any): Promise<{
        tags: string[];
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        location: string;
        slug: string;
        date: string;
        titleFr: string;
        titleEn: string | null;
        scope: string;
        descFr: string;
        descEn: string | null;
        images: string[];
        client: string | null;
        isFeatured: boolean;
        order: number;
    }>;
    update(id: string, updateDto: UpdateRealisationDto, req: any): Promise<{
        tags: string[];
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        location: string;
        slug: string;
        date: string;
        titleFr: string;
        titleEn: string | null;
        scope: string;
        descFr: string;
        descEn: string | null;
        images: string[];
        client: string | null;
        isFeatured: boolean;
        order: number;
    }>;
    remove(id: string, req: any): Promise<{
        message: string;
    }>;
    toggle(id: string, req: any): Promise<{
        tags: string[];
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        location: string;
        slug: string;
        date: string;
        titleFr: string;
        titleEn: string | null;
        scope: string;
        descFr: string;
        descEn: string | null;
        images: string[];
        client: string | null;
        isFeatured: boolean;
        order: number;
    }>;
    toggleFeatured(id: string, req: any): Promise<{
        tags: string[];
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        location: string;
        slug: string;
        date: string;
        titleFr: string;
        titleEn: string | null;
        scope: string;
        descFr: string;
        descEn: string | null;
        images: string[];
        client: string | null;
        isFeatured: boolean;
        order: number;
    }>;
}
